function cmt = makecmtsolution3d
% cmt = MAKECMTSOLUTION3D
%
% Makes sensible CMT solution parameters for SPECFEM3D_Cartesian simulation
%
% OUTPUT:
% cmt           CMT solutions, array of struct(s) with following fields
%               - HDR
%                   - TYPE
%                   - YEAR
%                   - MONTH
%                   - DAY
%                   - HOUR
%                   - MINUTE
%                   - SECOND
%                   - LAT
%                   - LON
%                   - DEPTH
%                   - mb
%                   - Ms
%                   - NAME
%               - NAME              event name
%               - TSHIFT            time shift
%               - HALFDUR           half duration
%               - LAT               latitude
%               - LON               longitude
%               - DEPTH             depth
%               - Mrr
%               - Mtt
%               - Mpp
%               - Mrt
%               - Mrp
%               - Mtp
%
% The CMT solution format can be found at
% https://specfem3d.readthedocs.io/en/latest/05_running_the_solver/
%
% SEE ALSO:
% LOADCMTSOLUTION3D, WRITECMTSOLUTION3D
%
% Last modified by sirawich-at-princeton.edu, 09/30/2024

hdr = struct(...
    'TYPE'      , 'XXXX'    , ...
    'YEAR'      , 2011      , ...
    'MONTH'     , 1         , ...
    'DAY'       , 1         , ...
    'HOUR'      , 1         , ...
    'MINUTE'    , 1         , ...
    'SECOND'    , 1.11      , ...
    'LAT'       , -11.11    , ...
    'LON'       , -111.11   , ...
    'DEPTH'     , 10        , ...
    'mb'        , 4.2       , ...
    'Ms'        , 4.4       , ...
    'NAME'      , 'EVENT 1'   ...
);

cmt = {struct(...
    'HDR'       , hdr       , ...
    'NAME'      , 'EVENT001', ...
    'TSHIFT'    , 0         , ...
    'HALFDUR'   , 0.1       , ...
    'LAT'       , -11.11    , ...
    'LON'       , -111.11   , ...
    'DEPTH'     , -10       , ...
    'Mrr'       , 1e+23     , ...
    'Mtt'       , 1e+23     , ...
    'Mpp'       , 1e+23     , ...
    'Mrt'       , 0e+23     , ...
    'Mrp'       , 0e+23     , ...
    'Mtp'       , 0e+23       ...
)};
end