function params = makeparams3d
% params = MAKEPARAMS3D
%
% Makes sensible parameters for Par_file of SPECFEM3D_Cartesian.
%
% SEE ALSO,
% LOADPARFILE3D, WRITEPARFILE3D
%
% Last modified by Sirawich Pipatprathanporn, 09/17/2024

params = struct(...
                    'SIMULATION_TYPE', 1                            , ...
                   'NOISE_TOMOGRAPHY', 0                            , ...
                       'SAVE_FORWARD', 0                            , ...
           'INVERSE_FWI_FULL_PROBLEM', 0                            , ...
                'UTM_PROJECTION_ZONE', 11                           , ...
            'SUPPRESS_UTM_PROJECTION', 1                            , ...
                              'NPROC', 8                            , ...
                              'NSTEP', 11111                        , ...
                                 'DT', 0.0045                       , ...
                           'LTS_MODE', 0                            , ...
                  'PARTITIONING_TYPE', 1                            , ...
                          'USE_LDDRK', 0                            , ...
             'INCREASE_CFL_FOR_LDDRK', 0                            , ...
      'RATIO_BY_WHICH_TO_INCREASE_IT', 1.4000                       , ...
                              'NGNOD', 8                            , ...
                              'MODEL', 'default'                    , ...
                    'TOMOGRAPHY_PATH', './DATA/tomo_files/'         , ...
                'SEP_MODEL_DIRECTORY', './DATA/my_SEP_model/'       , ...
             'APPROXIMATE_OCEAN_LOAD', 0                            , ...
                         'TOPOGRAPHY', 0                            , ...
                        'ATTENUATION', 0                            , ...
                         'ANISOTROPY', 0                            , ...
                            'GRAVITY', 0                            , ...
           'ATTENUATION_f0_REFERENCE', 0.3333                       , ...
             'MIN_ATTENUATION_PERIOD', 999999998                    , ...
             'MAX_ATTENUATION_PERIOD', 999999999                    , ...
        'COMPUTE_FREQ_BAND_AUTOMATIC', 1                            , ...
              'USE_OLSEN_ATTENUATION', 0                            , ...
            'OLSEN_ATTENUATION_RATIO', 0.0500                       , ...
                     'PML_CONDITIONS', 0                            , ...
        'PML_INSTEAD_OF_FREE_SURFACE', 0                            , ...
                         'f0_FOR_PML', 12.7000                      , ...
        'STACEY_ABSORBING_CONDITIONS', 1                            , ...
     'STACEY_INSTEAD_OF_FREE_SURFACE', 0                            , ...
                'BOTTOM_FREE_SURFACE', 0                            , ...
        'UNDO_ATTENUATION_AND_OR_PML', 0                            , ...
                'NT_DUMP_ATTENUATION', 500                          , ...
                    'CREATE_SHAKEMAP', 0                            , ...
                      'MOVIE_SURFACE', 0                            , ...
                         'MOVIE_TYPE', 1                            , ...
                       'MOVIE_VOLUME', 1                            , ...
                  'SAVE_DISPLACEMENT', 0                            , ...
                'MOVIE_VOLUME_STRESS', 0                            , ...
             'USE_HIGHRES_FOR_MOVIES', 0                            , ...
              'NTSTEP_BETWEEN_FRAMES', 100                          , ...
                         'HDUR_MOVIE', 0                            , ...
                    'SAVE_MESH_FILES', 1                            , ...
                         'LOCAL_PATH', './DATABASES_MPI'            , ...
         'NTSTEP_BETWEEN_OUTPUT_INFO', 500                          , ...
            'USE_SOURCES_RECEIVERS_Z', 1                            , ...
             'USE_FORCE_POINT_SOURCE', 0                            , ...
           'USE_RICKER_TIME_FUNCTION', 1                            , ...
           'USE_EXTERNAL_SOURCE_FILE', 0                            , ...
         'PRINT_SOURCE_TIME_FUNCTION', 1                            , ...
                'USE_SOURCE_ENCODING', 0                            , ...
      'NTSTEP_BETWEEN_OUTPUT_SEISMOS', 10000                        , ...
       'NTSTEP_BETWEEN_OUTPUT_SAMPLE', 1                            , ...
      'SAVE_SEISMOGRAMS_DISPLACEMENT', 1                            , ...
          'SAVE_SEISMOGRAMS_VELOCITY', 0                            , ...
      'SAVE_SEISMOGRAMS_ACCELERATION', 0                            , ...
          'SAVE_SEISMOGRAMS_PRESSURE', 1                            , ...
            'SAVE_SEISMOGRAMS_STRAIN', 0                            , ...
    'SAVE_SEISMOGRAMS_IN_ADJOINT_RUN', 0                            , ...
         'USE_BINARY_FOR_SEISMOGRAMS', 0                            , ...
                          'SU_FORMAT', 0                            , ...
                        'ASDF_FORMAT', 0                            , ...
                        'HDF5_FORMAT', 0                            , ...
          'WRITE_SEISMOGRAMS_BY_MAIN', 0                            , ...
       'SAVE_ALL_SEISMOS_IN_ONE_FILE', 0                            , ...
      'USE_TRICK_FOR_BETTER_PRESSURE', 0                            , ...
                      'OUTPUT_ENERGY', 0                            , ...
       'NTSTEP_BETWEEN_OUTPUT_ENERGY', 10                           , ...
         'NTSTEP_BETWEEN_READ_ADJSRC', 0                            , ...
                   'READ_ADJSRC_ASDF', 0                            , ...
                     'ANISOTROPIC_KL', 0                            , ...
                 'SAVE_TRANSVERSE_KL', 0                            , ...
            'ANISOTROPIC_VELOCITY_KL', 0                            , ...
                'APPROXIMATE_HESS_KL', 0                            , ...
                     'SAVE_MOHO_MESH', 0                            , ...
    'COUPLE_WITH_INJECTION_TECHNIQUE', 1                            , ...
           'INJECTION_TECHNIQUE_TYPE', 3                            , ...
          'MESH_A_CHUNK_OF_THE_EARTH', 0                            , ...
                      'TRACTION_PATH', './DATA/AxiSEM_tractions/1/' , ...
                       'FKMODEL_FILE', 'DATA/FKMODEL'               , ...
        'RECIPROCITY_AND_KH_INTEGRAL', 0                            , ...
        'NUMBER_OF_SIMULTANEOUS_RUNS', 1                            , ...
      'BROADCAST_SAME_MESH_AND_MODEL', 0                            , ...
                           'GPU_MODE', 0                            , ...
                      'ADIOS_ENABLED', 0                            , ...
                'ADIOS_FOR_DATABASES', 0                            , ...
                     'ADIOS_FOR_MESH', 0                            , ...
           'ADIOS_FOR_FORWARD_ARRAYS', 0                            , ...
                  'ADIOS_FOR_KERNELS', 0                            , ...
         'ADIOS_FOR_UNDO_ATTENUATION', 0                            , ...
                       'HDF5_ENABLED', 0                            , ...
                    'HDF5_FOR_MOVIES', 0                            , ...
                      'HDF5_IO_NODES', 0                              ...
    );
end