function meshparams = makemeshparams3d
% meshparams = MAKEMESHPARAMS3D
%
% Makes sensible mesh parameters for Par_file of SPECFEM3D_Cartesian.
%
% OUTPUT,
% meshparams        mesh parameters
%
% SEE ALSO,
% LOADMESHPARAMS3D, WRITEMESHPARAMS3D, MAKEPARAMS3D
%
% Last modified by sirawich-at-princeton.edu, 09/18/2024

% default materials
material1 = struct(...
    'rho'               , 3300          , ...
    'vp'                , 8031.15       , ...
    'vs'                , 4576.15       , ...
    'Q_Kappa'           , 9999          , ...
    'Q_mu'              , 9999          , ...
    'anisotropy_flag'   , 0             , ...
    'domain_id'         , 2              ...
);

material2 = struct(...
    'rho'               , 2677.5        , ...
    'vp'                , 5250          , ...
    'vs'                , 2835          , ...
    'Q_Kappa'           , 9999          , ...
    'Q_mu'              , 9999          , ...
    'anisotropy_flag'   , 0             , ...
    'domain_id'         , 2              ...
);

material3 = struct(...
    'rho'               , 1020          , ...
    'vp'                , 1500          , ...
    'vs'                , 0             , ...
    'Q_Kappa'           , 9999          , ...
    'Q_mu'              , 9999          , ...
    'anisotropy_flag'   , 0             , ...
    'domain_id'         , 1              ...
);

MATERIALS = {{material1; material2; material3}};

% default regions
region1 = struct(...
    'NEX_XI_BEGIN'      , 1             , ...
    'NEX_XI_END'        , 56            , ...
    'NEX_ETA_BEGIN'     , 1             , ...
    'NEX_ETA_END'       , 56            , ...
    'NZ_BEGIN'          , 11            , ...
    'NZ_END'            , 20            , ...
    'material_id'       , 3               ...
);

region2 = struct(...
    'NEX_XI_BEGIN'      , 1             , ...
    'NEX_XI_END'        , 56            , ...
    'NEX_ETA_BEGIN'     , 1             , ...
    'NEX_ETA_END'       , 56            , ...
    'NZ_BEGIN'          , 6             , ...
    'NZ_END'            , 10            , ...
    'material_id'       , 2               ...
);

region3 = struct(...
    'NEX_XI_BEGIN'      , 1             , ...
    'NEX_XI_END'        , 56            , ...
    'NEX_ETA_BEGIN'     , 1             , ...
    'NEX_ETA_END'       , 56            , ...
    'NZ_BEGIN'          , 1             , ...
    'NZ_END'            , 5             , ...
    'material_id'       , 1               ...
);

REGIONS = {{region1; region2; region3}};

meshparams = struct(...
               'LATITUDE_MIN', -14000               , ...
               'LATITUDE_MAX', 14000                , ...
              'LONGITUDE_MIN', -14000               , ...
              'LONGITUDE_MAX', 14000                , ...
             'DEPTH_BLOCK_KM', 10                   , ...
        'UTM_PROJECTION_ZONE', 11                   , ...
    'SUPPRESS_UTM_PROJECTION', 1                    , ...
            'INTERFACES_FILE', 'interfaces.dat'     , ...
                'CAVITY_FILE', 'no_cavity.dat'      , ...
                     'NEX_XI', 56                   , ...
                    'NEX_ETA', 56                   , ...
                   'NPROC_XI', 2                    , ...
                  'NPROC_ETA', 4                    , ...
           'USE_REGULAR_MESH', 1                    , ...
                 'NDOUBLINGS', 0                    , ...
               'NZ_DOUBLINGS', [11; 0]              , ...
        'CREATE_ABAQUS_FILES', 0                    , ...
            'CREATE_DX_FILES', 0                    , ...
           'CREATE_VTK_FILES', 1                    , ...
         'SAVE_MESH_AS_CUBIT', 0                    , ...
                 'LOCAL_PATH', './DATABASES_MPI'    , ...
         'THICKNESS_OF_X_PML', 12.3000              , ...
         'THICKNESS_OF_Y_PML', 12.3000              , ...
         'THICKNESS_OF_Z_PML', 12.3000              , ...
                 'NMATERIALS', 3                    , ...
                  'MATERIALS', MATERIALS            , ...
                   'NREGIONS', 3                    , ...
                    'REGIONS', REGIONS                ...
    );
end